=== GoogleCloudPlatform/cloud-solutions/projects/alloydb-autoscaler/src/autoscaler-core/schema/autoscaler-instance.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "autoscaler-instance.json",
  "title": "Autoscaleable Instance",
  "description": "Specification of an instance to be managed by the autoscaler.",
  "$comment": "Any changes to this file also need to be reflected in src/poller/README.md, and in src/common/instance-info.ts.",
  "type": "object",
  "additionalProperties": false,
  "required": ["projectId", "regionId"],
  "properties": {
    "$comment": {
      "type": "string"
    },

    "projectId": { "$ref": "autoscaler-core-defs.json#/$defs/projectId" },
    "regionId": { "$ref": "autoscaler-core-defs.json#/$defs/regionId" },

    "units": { "$ref": "autoscaler-core-defs.json#/$defs/units" },

    "minSize": { "$ref": "autoscaler-core-defs.json#/$defs/minSize" },
    "maxSize": { "$ref": "autoscaler-core-defs.json#/$defs/maxSize" },

    "scalingMethod": {
      "$ref": "autoscaler-core-defs.json#/$defs/scalingMethod"
    },

    "scalingProfile": {
      "$ref": "autoscaler-core-defs.json#/$defs/scalingProfile"
    },
    "scalingRules": {
      "$ref": "autoscaler-core-defs.json#/$defs/scalingRules"
    },

    "stepSize": { "$ref": "autoscaler-core-defs.json#/$defs/stepSize" },

    "scaleInLimit": { "$ref": "autoscaler-core-defs.json#/$defs/scaleInLimit" },
    "scaleOutLimit": {
      "$ref": "autoscaler-core-defs.json#/$defs/scaleOutLimit"
    },
    "scaleOutCoolingMinutes": {
      "$ref": "autoscaler-core-defs.json#/$defs/scaleOutCoolingMinutes"
    },
    "scaleInCoolingMinutes": {
      "$ref": "autoscaler-core-defs.json#/$defs/scaleInCoolingMinutes"
    },

    "scalerPubSubTopic": {
      "$ref": "autoscaler-core-defs.json#/$defs/scalerPubSubTopic"
    },
    "downstreamPubSubTopic": {
      "$ref": "autoscaler-core-defs.json#/$defs/downstreamPubSubTopic"
    },

    "stateProjectId": {
      "$ref": "autoscaler-core-defs.json#/$defs/stateProjectId"
    },
    "stateDatabase": {
      "$ref": "autoscaler-core-defs.json#/$defs/stateDatabase"
    }
  }
}

=== GoogleCloudPlatform/cloud-solutions/projects/alloydb-autoscaler/src/autoscaler-config-validator/test/resources/good-config-with-custom-rules.json
[
  {
    "projectId": "minimal-data",
    "regionId": "us-central1",
    "scalerPubSubTopic": "projects/my-project/topics/autoscaler-scaling",
    "minSize": 5,
    "maxSize": 30,
    "scalingMethod": "DIRECT",

    "scalingProfile": "CUSTOM",
    "scalingRules": [
      {
        "name": "custom_max_memory_rule",
        "conditions": {
          "all": [
            {
              "fact": "memory_maximum_utilization",
              "operator": "lessThan",
              "value": 70
            }
          ]
        },
        "event": {
          "type": "IN",
          "params": {
            "message": "low maximum memory utilization",
            "scalingMetrics": ["memory_maximum_utilization"]
          }
        },
        "priority": 1
      },
      {
        "name": "custom_average_memory_rule",
        "conditions": {
          "all": [
            {
              "fact": "memory_average_utilization",
              "operator": "lessThan",
              "value": 60
            }
          ]
        },
        "event": {
          "type": "IN",
          "params": {
            "message": "low average memory utilization",
            "scalingMetrics": ["memory_average_utilization"]
          }
        },
        "priority": 1
      }
    ]
  }
]

=== GoogleCloudPlatform/cloud-solutions/projects/alloydb-autoscaler/src/autoscaler-config-validator/test/resources/good-config.json
[
  {
    "projectId": "minimal-data",
    "regionId": "us-central1",
    "scalerPubSubTopic": "projects/my-project/topics/autoscaler-scaling",
    "minSize": 5,
    "maxSize": 30,
    "scalingMethod": "DIRECT"
  },
  {
    "projectId": "complete-data",
    "regionId": "us-central1",

    "minSize": 3,
    "maxSize": 10,

    "scalingMethod": "STEPWISE",
    "scaleInLimit": 1,
    "scaleOutLimit": 3,
    "scaleOutCoolingMinutes": 10,
    "scaleInCoolingMinutes": 60,

    "scalerPubSubTopic": "projects/my-project/topics/autoscaler-scaling",
    "downstreamPubSubTopic": "projects/my-project/topics/autoscaler-downstream",

    "stateProjectId": "state-project-id",
    "stateDatabase": {
      "instanceId": "state-instance-id",
      "databaseId": "state-database-id"
    }
  },
  {
    "projectId": "partial-data",
    "regionId": "us-central1",
    "minSize": 3,
    "maxSize": 10,
    "scalingMethod": "LINEAR",
    "scaleOutCoolingMinutes": 10,
    "scaleInCoolingMinutes": 60,
    "scalerPubSubTopic": "projects/my-project/topics/autoscaler-scaling"
  }
]
